name: pytorch
channels:
  - pytorch
  - fastai
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - pillow
  - requests
  - numpy
  - scipy
  - pytorch 
  - torchvision 
  - cudatoolkit=9.0
  - pip:
    - gradient-statsd
