name: pytorch
channels:
  - pytorch
  - fastai
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - pillow
  - requests
  - numpy=1.16.1
  - scipy
  - pytorch 
  - torchvision 
  - cudatoolkit=9.0
  - pandas
  - pip:
    - gradient-statsd
